FROM node:lts-alpine

RUN npm install -g http-server

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG VUE_APP_CURRENT
ARG VUE_APP_FIREBASE_API_KEY
ARG VUE_APP_FIREBASE_AUTH_DOMAIN
ARG VUE_APP_FIREBASE_PROJECT_ID
ARG VUE_APP_FIREBASE_STORAGE_BUCKET
ARG VUE_APP_FIREBASE_MESSAGING_SENDER_ID
ARG VUE_APP_FIREBASE_APP_ID
ARG VUE_APP_FIREBASE_PATH
ARG VUE_APP_FIREBASE_PATH_TICKETS

ENV VUE_APP_CURRENT='http://clayrite.ddns.net:81'
ENV VUE_APP_FIREBASE_API_KEY=${FIREBASE_API_KEY}
ENV VUE_APP_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
ENV VUE_APP_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
ENV VUE_APP_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
ENV VUE_APP_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
ENV VUE_APP_FIREBASE_APP_ID=${FIREBASE_APP_ID}
ENV VUE_APP_FIREBASE_PATH='images/dev/productos/'
ENV VUE_APP_FIREBASE_PATH_TICKETS='dev/tickets/'

RUN npm run build

EXPOSE 80

CMD ["http-server", "-p 80", "dist"]