name: 'Construir imagen de Docker'

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Version o tag de la imagen
        required: true
        default: latest

jobs:
  build_image:
    runs-on:
      ubuntu-latest
  steps:
    - name: Checkout codigo
      uses: actions/checkout@v2
    
    - name: Login a dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.EDSON_DOCKERHUB_ID }}
        password: ${{ secrets.EDSON_DOCKERHUB_TOKEN }}
    
    - name: Configurar QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Configurar BuildX
      uses: docker/setup-buildx-action@v1.0.0

    - name: Construir imagen de docker
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        tags: ${{ secrets.EDSON_DOCKERHUB_ID }}/sharedz_vue:${{ github.event.inputs.tag }}
        platforms: linux/amd64, linux/arm64
        push: true