name: "🚀Desplegar con Netlify"

on:
  workflow_dispatch

jobs:
  merge_to_deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codigo
      uses: actions/checkout@v2

    - name: Update deployment
      uses: everlytic/branch-merge@1.1.5
      with:
        target_branch: deployment
        github_token: ${{ secrets.XATAL_GITHUB_TOKEN }}
        source_ref: ${{ github.ref }}
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
